apiVersion: v2
name: trace-inventory
description: A Helm chart for Trace Demo Inventory Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservice
  - inventory
  - spring-boot
maintainers:
  - name: Trace Demo Team
    email: team@trace-demo.com
